import { Link } from 'react-router-dom'
import { ArrowLeft } from 'lucide-react'

function LegalLayout({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="w-full max-w-3xl mx-auto py-6 px-4">
      <Link to="/" className="inline-flex items-center gap-1.5 text-[13px] text-text-muted hover:text-text-primary mb-6">
        <ArrowLeft className="h-4 w-4" /> Back to Feed
      </Link>
      <h1 className="text-2xl font-bold mb-6">{title}</h1>
      <div className="prose prose-sm text-text-secondary space-y-4 [&_h2]:text-lg [&_h2]:font-semibold [&_h2]:text-text-primary [&_h2]:mt-6 [&_h2]:mb-2 [&_p]:leading-relaxed [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:space-y-1">
        {children}
      </div>
    </div>
  )
}

export function PrivacyPage() {
  return (
    <LegalLayout title="Privacy Policy">
      <p>Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>

      <h2>1. Information We Collect</h2>
      <p>When you create an account, we collect your email address, name, and profile information you provide during onboarding (skills, interests, experience level). We also collect usage data such as ideas you view and votes you cast.</p>

      <h2>2. How We Use Your Information</h2>
      <ul>
        <li>To generate personalized SaaS ideas based on your skills and interests</li>
        <li>To maintain your account and provide our services</li>
        <li>To improve the quality of AI-generated ideas using aggregated feedback</li>
        <li>To display public content such as shared ideas and vote counts</li>
      </ul>

      <h2>3. Data Storage</h2>
      <p>Your data is stored securely on Supabase infrastructure with row-level security policies. Private ideas are only accessible to you unless you explicitly choose to share them publicly.</p>

      <h2>4. Third-Party Services</h2>
      <p>We use OpenRouter API to generate SaaS ideas. When generating ideas, your skills and interests may be sent to the AI model to personalize results. No personally identifiable information is shared.</p>

      <h2>5. Your Rights</h2>
      <ul>
        <li>Access and download your data at any time</li>
        <li>Delete your account and all associated data</li>
        <li>Control the visibility of your ideas (public or private)</li>
        <li>Opt out of personalized idea generation</li>
      </ul>

      <h2>6. Contact</h2>
      <p>For privacy-related questions, contact us at privacy@opensaasidea.com.</p>
    </LegalLayout>
  )
}

export function TermsPage() {
  return (
    <LegalLayout title="User Agreement">
      <p>Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>

      <h2>1. Acceptance of Terms</h2>
      <p>By using OpenSaaSIdea, you agree to these terms. If you do not agree, please do not use our service.</p>

      <h2>2. Service Description</h2>
      <p>OpenSaaSIdea is an AI-powered platform that generates SaaS business ideas. Ideas are generated by artificial intelligence and should be treated as starting points for further research and validation, not as guaranteed business plans.</p>

      <h2>3. Account Responsibilities</h2>
      <ul>
        <li>You must provide accurate information when creating an account</li>
        <li>You are responsible for maintaining the security of your account</li>
        <li>You must be at least 18 years old to use this service</li>
      </ul>

      <h2>4. Content Ownership</h2>
      <p>Ideas generated through our platform are provided as-is. You are free to use, modify, and build upon any idea generated for you. We do not claim ownership over ideas generated for your account. Public ideas shared to the community feed are viewable by all users.</p>

      <h2>5. Acceptable Use</h2>
      <ul>
        <li>Do not attempt to manipulate vote counts or abuse the voting system</li>
        <li>Do not use automated tools to scrape or bulk-download ideas</li>
        <li>Do not impersonate other users</li>
      </ul>

      <h2>6. Disclaimers</h2>
      <p>AI-generated ideas may contain inaccuracies. Revenue estimates, market analysis, and competitor information are approximations and should not be relied upon without independent verification. We are not liable for business decisions made based on generated ideas.</p>

      <h2>7. Changes to Terms</h2>
      <p>We may update these terms at any time. Continued use of the service constitutes acceptance of updated terms.</p>
    </LegalLayout>
  )
}

export function AccessibilityPage() {
  return (
    <LegalLayout title="Accessibility">
      <p>Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>

      <h2>Our Commitment</h2>
      <p>OpenSaaSIdea is committed to ensuring digital accessibility for all users. We strive to conform to WCAG 2.1 Level AA standards and continuously improve the user experience for everyone.</p>

      <h2>Accessibility Features</h2>
      <ul>
        <li>Full keyboard navigation support</li>
        <li>Light and dark theme modes for visual comfort</li>
        <li>Semantic HTML structure for screen reader compatibility</li>
        <li>Sufficient color contrast ratios across all UI elements</li>
        <li>Responsive design that works across all device sizes</li>
        <li>Clear focus indicators for interactive elements</li>
      </ul>

      <h2>Known Limitations</h2>
      <p>Some AI-generated content may not be optimally structured for screen readers. We are working to improve the formatting of generated idea breakdowns.</p>

      <h2>Feedback</h2>
      <p>If you experience any accessibility issues, please contact us at accessibility@opensaasidea.com. We take all feedback seriously and will work to address issues promptly.</p>
    </LegalLayout>
  )
}
